baseURL = "https://example.com"
languageCode = "en-us"
title = "A promising attempt at publishing a website from org-mode"
theme = ["github.com/onweru/compose"] # edit this if you'ld rather use a fork of this repo
enableEmoji=true

[Params]
  indexPager = false
  cleanDestinationDir = true
  toc = true
  twitter_cars = true
  post_navigation = true
  # author = ["FirstName LastName"]
  tags = ["theory","practical"]
  authorbox = true
  BookMenuBundle = "/menu"

[outputs]
  home = ["HTML", "RSS","JSON"]


[Author] # Used in authorbox
  name = "John Doe"
  bio = "John Doe's true identity is unknown. Maybe he is a successful blogger or writer."


[Params.Widgets]
  search = true
  recent_articles = true
  categories = true

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/"
  [[menu.main]]
    identifier = "spacemacs"
    name       = "Spacemacs"
    url        = "/docs/spacemacs"
  [[menu.main]]
    identifier = "bash"
    name       = "Bash"
    url        = "/docs/bash"







