baseURL = "https://example.com"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "binario"

[Params]
  indexPager = false
  mainSections =["posts","about"]
  cleanDestinationDir = true
  toc = true
  twitter_cars = true